In [1]:
#Importing Dataset
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)
accepted_loans = pd.read_csv(r"C:\Users\drobey\Documents\Coding\Grad School\Data Platforms\Project\accepted_2007_to_2018Q4.csv")

C:\Users\drobey\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
#View it
accepted_loans.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.00,0.00,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.00,0.00,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.00,0.00,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,NaN,NaN,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.010000,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.90,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.00,0.00,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Get List of column names
list(accepted_loans.columns)

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [4]:
#drop all rows we judgementally determined not to include
accepted_loans = accepted_loans.drop([
'all_util',
'avg_cur_bal',
'bc_open_to_buy',
'bc_util',
'chargeoff_within_12_mths',
'collection_recovery_fee',
'collections_12_mths_ex_med',
'delinq_2yrs',
'delinq_amnt',
'dti',
'dti_joint',
'earliest_cr_line',
'il_util',
'initial_list_status',
'last_credit_pull_d',
'last_fico_range_high',
'last_fico_range_low',
'last_pymnt_amnt',
'last_pymnt_d',
'max_bal_bc',
'member_id',
'mths_since_last_delinq',
'mths_since_last_major_derog',
'mths_since_recent_revol_delinq',
'next_pymnt_d',
'num_tl_90g_dpd_24m',
'open_il_24m',
'open_rv_24m',
'out_prncp',
'out_prncp_inv',
'policy_code',
'pymnt_plan',
'recoveries',
'revol_bal',
'revol_util',
'tax_liens',
'term',
'tot_coll_amt',
'tot_cur_bal',
'tot_hi_cred_lim',
'total_bal_ex_mort',
'total_bal_il',
'total_bc_limit',
'total_il_high_credit_limit',
'total_pymnt',
'total_pymnt_inv',
'total_rec_int',
'total_rec_late_fee',
'total_rec_prncp',
'total_rev_hi_lim',
'url',
'verification_status',
'verification_status_joint',
'zip_code',
'revol_bal_joint', 
'hardship_flag',
'hardship_type',
'hardship_reason',
'hardship_status',
'deferral_term',
'hardship_amount',
'hardship_start_date',
'hardship_end_date',
'payment_plan_start_date',
'hardship_length',
'hardship_dpd',
'hardship_loan_status',
'orig_projected_additional_accrued_interest',
'hardship_payoff_balance_amount',
'hardship_last_payment_amount',
'disbursement_method',
'debt_settlement_flag',
'debt_settlement_flag_date',
'settlement_status',
'settlement_date',
'settlement_amount',
'settlement_percentage',
'settlement_term',
'issue_d'], axis=1)

In [5]:
#Find which columns have a large amt of NA values
nan_mean = accepted_loans.isna().mean()
nan_mean = nan_mean[nan_mean != 0].sort_values()
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(nan_mean)

loan_amnt                              0.000015
addr_state                             0.000015
purpose                                0.000015
loan_status                            0.000015
home_ownership                         0.000015
fico_range_low                         0.000015
application_type                       0.000015
grade                                  0.000015
installment                            0.000015
int_rate                               0.000015
funded_amnt_inv                        0.000015
funded_amnt                            0.000015
sub_grade                              0.000015
fico_range_high                        0.000015
annual_inc                             0.000016
acc_now_delinq                         0.000027
total_acc                              0.000027
pub_rec                                0.000027
open_acc                               0.000027
inq_last_6mths                         0.000028
pub_rec_bankruptcies                   0.000618
title                                  0.010332
mort_acc                               0.022145
acc_open_past_24mths                   0.022145
num_sats                               0.025931
num_bc_sats                            0.025931
num_tl_op_past_12m                     0.031101
mo_sin_rcnt_tl                         0.031101
num_actv_bc_tl                         0.031101
num_actv_rev_tl                        0.031101
num_bc_tl                              0.031101
num_il_tl                              0.031101
num_rev_tl_bal_gt_0                    0.031101
num_tl_30dpd                           0.031101
num_op_rev_tl                          0.031101
num_accts_ever_120_pd                  0.031101
num_rev_accts                          0.031101
mo_sin_old_rev_tl_op                   0.031101
mo_sin_rcnt_rev_tl_op                  0.031101
pct_tl_nvr_dlq                         0.031169
mths_since_recent_bc                   0.032488
percent_bc_gt_75                       0.033358
mo_sin_old_il_acct                     0.061531
emp_length                             0.064998
num_tl_120dpd_2m                       0.067983
emp_title                              0.073872
mths_since_recent_inq                  0.130698
inq_fi                                 0.383139
open_rv_12m                            0.383139
open_il_12m                            0.383139
open_act_il                            0.383139
inq_last_12m                           0.383139
total_cu_tl                            0.383139
open_acc_6m                            0.383139
mths_since_rcnt_il                     0.402511
mths_since_recent_bc_dlq               0.770115
mths_since_last_record                 0.841131
desc                                   0.944235
annual_inc_joint                       0.946605
sec_app_collections_12_mths_ex_med     0.952218
sec_app_fico_range_low                 0.952218
sec_app_fico_range_high                0.952218
sec_app_earliest_cr_line               0.952218
sec_app_inq_last_6mths                 0.952218
sec_app_mort_acc                       0.952218
sec_app_open_acc                       0.952218
sec_app_open_act_il                    0.952218
sec_app_num_rev_accts                  0.952218
sec_app_chargeoff_within_12_mths       0.952218
sec_app_revol_util                     0.953030
sec_app_mths_since_last_major_derog    0.984101
dtype: float64

In [6]:
#Drop rows with NAs in these columns
accepted_loans.dropna(subset = ["loan_amnt","annual_inc","acc_now_delinq"], inplace=True)

In [7]:
#Drop rows related to secondary (very empty and would potentially throw off model)
accepted_loans = accepted_loans.drop([
'annual_inc_joint',                  
'sec_app_fico_range_low',                
'sec_app_fico_range_high',               
'sec_app_earliest_cr_line',              
'sec_app_inq_last_6mths',                
'sec_app_mort_acc',                      
'sec_app_open_acc',                      
'sec_app_open_act_il',                   
'sec_app_num_rev_accts',                 
'sec_app_chargeoff_within_12_mths',      
'sec_app_collections_12_mths_ex_med',    
'sec_app_revol_util',
'sec_app_mths_since_last_major_derog'], axis=1)

In [9]:
#Fill string NA rows with empty strings
#Fill columns related to months since XXX that have NA with the max amount (assumption we made) 
fill_empty = ['emp_title','title','desc']
fill_max = ['mo_sin_rcnt_tl', 'mo_sin_old_rev_tl_op',
            'mo_sin_rcnt_rev_tl_op', 'mths_since_recent_bc',
            'mo_sin_old_il_acct', 'mths_since_recent_inq', 'mths_since_recent_bc_dlq',
            'pct_tl_nvr_dlq','mths_since_rcnt_il','mths_since_last_record']


accepted_loans[fill_empty] = accepted_loans[fill_empty].fillna('')
accepted_loans[fill_max] = accepted_loans[fill_max].fillna(accepted_loans[fill_max].max())

In [10]:
#Fix some data issues with emp_lenth and id
accepted_loans['emp_length'] = accepted_loans['emp_length'].replace({'< 1 year': '0 years', '10+ years': '11 years'})
accepted_loans['emp_length'] = accepted_loans['emp_length'].str.extract('(\d+)').astype('float')
accepted_loans['id'] = accepted_loans['id'].astype('float')

In [11]:
#Fill columns related to "num of XXX" to 0 if NA
fill_min = ['inq_last_6mths',
'pub_rec_bankruptcies',                  
'mort_acc',                              
'acc_open_past_24mths',                  
'num_bc_sats',                           
'num_sats',                              
'num_actv_bc_tl',                        
'num_accts_ever_120_pd',                 
'num_bc_tl',                             
'num_op_rev_tl',                         
'num_actv_rev_tl',                       
'num_rev_tl_bal_gt_0',                   
'num_tl_30dpd',                          
'num_tl_op_past_12m',                    
'num_il_tl',                             
'num_rev_accts',                         
'percent_bc_gt_75',                      
'emp_length',                            
'num_tl_120dpd_2m',                      
'inq_fi',                                
'open_rv_12m',                           
'open_il_12m',                           
'open_act_il',                           
'total_cu_tl',                           
'open_acc_6m',                           
'inq_last_12m']


accepted_loans[fill_min] = accepted_loans[fill_min].fillna(accepted_loans[fill_min].min())

In [12]:
#Make sure we have taken care of all NA values
nan_mean = accepted_loans.isna().mean()
nan_mean = nan_mean[nan_mean != 0].sort_values()
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(nan_mean)

Series([], dtype: float64)

In [13]:
accepted_loans.head()
accepted_loans.columns

Index(['id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'int_rate',
       'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length',
       'home_ownership', 'annual_inc', 'loan_status', 'desc', 'purpose',
       'title', 'addr_state', 'fico_range_low', 'fico_range_high',
       'inq_last_6mths', 'mths_since_last_record', 'open_acc', 'pub_rec',
       'total_acc', 'application_type', 'acc_now_delinq', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'mths_since_rcnt_il', 'open_rv_12m',
       'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths',
       'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op',
       'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_bc_dlq', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
       'percent_bc_gt_75', 'pub_rec_bankruptcies'],
      dtype='object')

In [15]:
#Import operational data into mySQL
#Important to run SQL code before this though
from sqlalchemy import create_engine

# create sqlalchemy engine
engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user="root",
                               pw="rootroot",
                               db="loan_data_operational"))

accepted_loans.to_sql('loan_details_main', con = engine, if_exists = 'append', chunksize = 1000)

In [16]:
import pymysql

# create connection
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='rootroot',
                             db='loan_data_operational')

# Create cursor
my_cursor = connection.cursor()

# Execute Query
my_cursor.execute("SELECT * from loan_details_main LIMIT 10")

# Fetch the records
result = my_cursor.fetchall()

for i in result:
    print(i)

# Close the connection
connection.close()

(0, 68407277.0, 3600.0, 3600.0, 3600.0, 13.99, 123.03, 'C', 'C4', 'leadman', 11.0, 'MORTGAGE', 55000.0, 'Fully Paid', '', 'debt_consolidation', 'Debt consolidation', 'PA', 675.0, 679.0, 1.0, 129.0, 7.0, 0.0, 13.0, 'Individual', 0.0, 2.0, 2.0, 0.0, 21.0, 3.0, 3.0, 1.0, 4.0, 4.0, 148.0, 128.0, 3.0, 3.0, 1.0, 4.0, 69.0, 4.0, 2.0, 2.0, 4.0, 2.0, 5.0, 3.0, 4.0, 9.0, 4.0, 7.0, 0.0, 0.0, 3.0, 76.9, 0.0, 0.0)
(1, 68355089.0, 24700.0, 24700.0, 24700.0, 11.99, 820.28, 'C', 'C1', 'Engineer', 11.0, 'MORTGAGE', 65000.0, 'Fully Paid', '', 'small_business', 'Business', 'SD', 715.0, 719.0, 4.0, 129.0, 22.0, 0.0, 38.0, 'Individual', 0.0, 1.0, 1.0, 0.0, 19.0, 2.0, 0.0, 0.0, 6.0, 4.0, 113.0, 192.0, 2.0, 2.0, 4.0, 2.0, 202.0, 0.0, 0.0, 5.0, 5.0, 13.0, 17.0, 6.0, 20.0, 27.0, 5.0, 22.0, 0.0, 0.0, 2.0, 97.4, 7.7, 0.0)
(2, 68341763.0, 20000.0, 20000.0, 20000.0, 10.78, 432.66, 'B', 'B4', 'truck driver', 11.0, 'MORTGAGE', 63000.0, 'Fully Paid', '', 'home_improvement', '', 'IL', 695.0, 699.0, 0.0, 129.0, 6.0, 0.0, 18.0, 'Joint App', 0.0, 0.0, 1.0, 0.0, 19.0, 0.0, 2.0, 5.0, 1.0, 6.0, 125.0, 184.0, 14.0, 14.0, 5.0, 101.0, 202.0, 10.0, 0.0, 2.0, 3.0, 2.0, 4.0, 6.0, 4.0, 7.0, 3.0, 6.0, 0.0, 0.0, 0.0, 100.0, 50.0, 0.0)
(3, 66310712.0, 35000.0, 35000.0, 35000.0, 14.85, 829.9, 'C', 'C5', 'Information Systems Officer', 11.0, 'MORTGAGE', 110000.0, 'Current', '', 'debt_consolidation', 'Debt consolidation', 'NJ', 785.0, 789.0, 0.0, 129.0, 13.0, 0.0, 17.0, 'Individual', 0.0, 1.0, 1.0, 0.0, 23.0, 1.0, 0.0, 1.0, 0.0, 2.0, 36.0, 87.0, 2.0, 2.0, 1.0, 2.0, 202.0, 25.0, 0.0, 4.0, 5.0, 8.0, 10.0, 2.0, 10.0, 13.0, 5.0, 13.0, 0.0, 0.0, 1.0, 100.0, 0.0, 0.0)
(4, 68476807.0, 10400.0, 10400.0, 10400.0, 22.45, 289.91, 'F', 'F1', 'Contract Specialist', 3.0, 'MORTGAGE', 104433.0, 'Fully Paid', '', 'major_purchase', 'Major purchase', 'PA', 695.0, 699.0, 3.0, 129.0, 12.0, 0.0, 35.0, 'Individual', 0.0, 1.0, 3.0, 0.0, 14.0, 4.0, 2.0, 1.0, 3.0, 10.0, 128.0, 210.0, 4.0, 4.0, 6.0, 4.0, 12.0, 1.0, 0.0, 4.0, 6.0, 5.0, 9.0, 10.0, 7.0, 19.0, 6.0, 12.0, 0.0, 0.0, 4.0, 96.6, 60.0, 0.0)
(5, 68426831.0, 11950.0, 11950.0, 11950.0, 13.44, 405.18, 'C', 'C3', 'Veterinary Tecnician', 4.0, 'RENT', 34000.0, 'Fully Paid', '', 'debt_consolidation', 'Debt consolidation', 'GA', 690.0, 694.0, 0.0, 129.0, 5.0, 0.0, 6.0, 'Individual', 0.0, 0.0, 1.0, 0.0, 338.0, 0.0, 0.0, 0.0, 0.0, 0.0, 338.0, 54.0, 32.0, 32.0, 0.0, 36.0, 202.0, 25.0, 0.0, 2.0, 3.0, 2.0, 2.0, 2.0, 4.0, 4.0, 3.0, 5.0, 0.0, 0.0, 0.0, 100.0, 100.0, 0.0)
(6, 68476668.0, 20000.0, 20000.0, 20000.0, 9.17, 637.58, 'B', 'B2', 'Vice President of Recruiting Operations', 11.0, 'MORTGAGE', 180000.0, 'Fully Paid', '', 'debt_consolidation', 'Debt consolidation', 'MN', 680.0, 684.0, 0.0, 129.0, 12.0, 0.0, 27.0, 'Individual', 0.0, 0.0, 2.0, 0.0, 18.0, 2.0, 1.0, 0.0, 1.0, 6.0, 142.0, 306.0, 10.0, 10.0, 4.0, 12.0, 202.0, 10.0, 0.0, 4.0, 6.0, 4.0, 5.0, 7.0, 9.0, 16.0, 6.0, 12.0, 0.0, 0.0, 2.0, 96.3, 100.0, 0.0)
(7, 67275481.0, 20000.0, 20000.0, 20000.0, 8.49, 631.26, 'B', 'B1', 'road driver', 11.0, 'MORTGAGE', 85000.0, 'Fully Paid', '', 'major_purchase', 'Major purchase', 'SC', 705.0, 709.0, 0.0, 129.0, 8.0, 0.0, 15.0, 'Individual', 0.0, 0.0, 3.0, 0.0, 13.0, 0.0, 1.0, 0.0, 2.0, 4.0, 149.0, 55.0, 32.0, 13.0, 3.0, 32.0, 202.0, 8.0, 1.0, 2.0, 2.0, 3.0, 3.0, 9.0, 3.0, 3.0, 2.0, 8.0, 0.0, 0.0, 0.0, 93.3, 0.0, 0.0)
(8, 68466926.0, 10000.0, 10000.0, 10000.0, 6.49, 306.45, 'A', 'A2', 'SERVICE MANAGER', 6.0, 'RENT', 85000.0, 'Fully Paid', '', 'credit_card', 'Credit card refinancing', 'PA', 685.0, 689.0, 1.0, 106.0, 14.0, 1.0, 23.0, 'Individual', 0.0, 2.0, 1.0, 0.0, 35.0, 2.0, 2.0, 0.0, 1.0, 7.0, 164.0, 129.0, 1.0, 1.0, 1.0, 4.0, 202.0, 1.0, 0.0, 6.0, 9.0, 7.0, 10.0, 3.0, 13.0, 19.0, 9.0, 14.0, 0.0, 0.0, 2.0, 95.7, 28.6, 1.0)
(9, 68616873.0, 8000.0, 8000.0, 8000.0, 11.48, 263.74, 'B', 'B5', 'Vendor liaison', 11.0, 'MORTGAGE', 42000.0, 'Fully Paid', '', 'credit_card', 'Credit card refinancing', 'RI', 700.0, 704.0, 0.0, 129.0, 8.0, 0.0, 18.0, 'Individual', 0.0, 0.0, 2.0, 2.0, 10.0, 0.0, 0.0, 0.0, 1.0, 5.0, 155.0, 253.0, 15.0, 10.0, 1.0, 50.0, 202.0, 10.0, 1.0, 3.0, 3.0, 3.0, 6.0, 5.0, 5.0, 11.0, 3.0, 8.0, 0.0, 0.0, 2.0, 94.4, 33.3, 0.0)

In [18]:
#See how many unique values each categorial variable has 
cat_feat = accepted_loans.select_dtypes('object').columns.values
accepted_loans[cat_feat].nunique().sort_values()

application_type         2
home_ownership           6
grade                    7
loan_status              9
purpose                 14
sub_grade               35
addr_state              51
title                63142
desc                124474
emp_title           512682
dtype: int64

In [19]:
#As we can see, title, desc and emp_title have a lot of different values.Would cause memory problems.
#Would be value in NLP with these columns, but beyond scope for us
#Also we want to get rid of sub_grade (we know is highly correlated with grade)
accepted_loans = accepted_loans.drop(['title', 'desc','emp_title','sub_grade'], axis=1, errors='ignore')

In [20]:
#Used to calculate pearson correlation between the various column
import numpy as np
from itertools import combinations
from scipy.stats import pearsonr
num_feat = accepted_loans.select_dtypes('number').columns.values
comb_num_feat = np.array(list(combinations(num_feat, 2)))
corr_num_feat = np.array([])
for comb in comb_num_feat:
    corr = pearsonr(accepted_loans[comb[0]], accepted_loans[comb[1]])[0]
    corr_num_feat = np.append(corr_num_feat, corr)

In [21]:
#Viewing these
high_corr_num = comb_num_feat[np.abs(corr_num_feat) >= 0.9]
high_corr_num

array([['loan_amnt', 'funded_amnt'],
       ['loan_amnt', 'funded_amnt_inv'],
       ['loan_amnt', 'installment'],
       ['funded_amnt', 'funded_amnt_inv'],
       ['funded_amnt', 'installment'],
       ['funded_amnt_inv', 'installment'],
       ['fico_range_low', 'fico_range_high'],
       ['open_acc', 'num_sats'],
       ['mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl'],
       ['num_actv_rev_tl', 'num_rev_tl_bal_gt_0']], dtype='<U24')

In [22]:
#Dropping the second one in each pair bc I wanted to keep loan_amnt 
accepted_loans = accepted_loans.drop(np.unique(high_corr_num[:, 1]), axis=1, errors='ignore')

In [23]:
#How many loans are in each status
my_list = accepted_loans['loan_status'].value_counts()
my_list

Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1962
Does not meet the credit policy. Status:Charged Off        758
Default                                                     40
Name: loan_status, dtype: int64

In [24]:
#We considered loans with status Current, Fully Paid, and In Grace Period as good. 
#All the other statuses are considered as bad loans (late 16-30 days, Late 31-120 days, or default) 
y = accepted_loans['loan_status'].copy()
y = y.isin(['Current', 'Fully Paid','In Grace Period','Does not meet the credit policy. Status:Fully Paid']).astype('int')
y.value_counts()

1    1965466
0     295173
Name: loan_status, dtype: int64

In [25]:
X_f = accepted_loans['grade'].copy()

In [26]:
X_f.value_counts()

B    663547
C    650047
A    433016
D    324423
E    135638
F     41800
G     12168
Name: grade, dtype: int64

In [30]:
#Only concerned with high risk/high reward loans. So we focus on grades with E F and G
#Remove grade/interest rate after selecting the high risk ones (and therefore high interest rate loans)
#Also remove loan status as that's now our y variable
X = accepted_loans[(accepted_loans.grade == 'E') | (accepted_loans.grade == 'F') | (accepted_loans.grade == 'G')].copy()
X.drop
X = X.drop(['grade', 'int_rate','loan_status','addr_state'], axis=1, errors='ignore')

In [32]:
#Also drop ID since it is no longer relevant
X = X.drop(['id'], axis = 1)

In [33]:
X.head()

,loan_amnt,emp_length,home_ownership,annual_inc,purpose,fico_range_low,inq_last_6mths,mths_since_last_record,open_acc,pub_rec,total_acc,application_type,acc_now_delinq,open_acc_6m,open_act_il,open_il_12m,mths_since_rcnt_il,open_rv_12m,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_tl_120dpd_2m,num_tl_30dpd,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies
4,10400.0,3.0,MORTGAGE,104433.0,major_purchase,695.0,3.0,129.0,12.0,0.0,35.0,Individual,0.0,1.0,3.0,0.0,14.0,4.0,2.0,1.0,3.0,10.0,128.0,210.0,4.0,6.0,4.0,12.0,1.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,0.0,0.0,4.0,96.6,60.0,0.0
13,18000.0,7.0,RENT,150000.0,debt_consolidation,665.0,1.0,75.0,18.0,1.0,27.0,Individual,0.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,7.0,115.0,112.0,1.0,2.0,9.0,202.0,2.0,0.0,6.0,13.0,7.0,8.0,6.0,16.0,19.0,0.0,0.0,3.0,100.0,14.3,1.0
19,8650.0,8.0,RENT,55000.0,debt_consolidation,675.0,4.0,30.0,18.0,1.0,19.0,Individual,0.0,6.0,1.0,0.0,19.0,12.0,2.0,0.0,5.0,17.0,129.0,95.0,0.0,0.0,8.0,202.0,0.0,0.0,2.0,17.0,2.0,2.0,2.0,17.0,17.0,0.0,0.0,12.0,100.0,50.0,1.0
31,24250.0,4.0,MORTGAGE,75000.0,debt_consolidation,660.0,0.0,129.0,18.0,0.0,21.0,Individual,0.0,2.0,1.0,0.0,14.0,2.0,1.0,1.0,3.0,13.0,93.0,104.0,2.0,2.0,2.0,202.0,7.0,0.0,10.0,12.0,11.0,12.0,2.0,15.0,16.0,0.0,0.0,3.0,100.0,63.6,0.0
48,14650.0,2.0,RENT,43160.0,debt_consolidation,690.0,0.0,129.0,12.0,0.0,24.0,Individual,0.0,0.0,10.0,0.0,76.0,0.0,0.0,0.0,0.0,0.0,122.0,45.0,40.0,0.0,40.0,202.0,25.0,0.0,2.0,2.0,2.0,2.0,22.0,2.0,2.0,0.0,0.0,0.0,100.0,100.0,0.0

In [34]:
#Only get the y values for which there is an X
y_mod = y[X.index]

In [35]:
#Combining the y and X variables into one dataframe
X_2 = pd.concat([y_mod, X], axis=1)

In [36]:
#normalizing the data
from sklearn import preprocessing
X_3 = X_2.drop(['application_type', 'home_ownership','purpose'],axis=1)
X_array = X_3.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(X_array)
X_norm=pd.DataFrame(x_scaled, columns=X_3.columns)
X_norm.head()

,loan_status,loan_amnt,emp_length,annual_inc,fico_range_low,inq_last_6mths,mths_since_last_record,open_acc,pub_rec,total_acc,acc_now_delinq,open_acc_6m,open_act_il,open_il_12m,mths_since_rcnt_il,open_rv_12m,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_tl_120dpd_2m,num_tl_30dpd,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies
0,1.0,0.248731,0.272727,0.012286,0.361702,0.090909,1.000000,0.136364,0.000000,0.211180,0.0,0.0625,0.056604,0.00,0.027397,0.153846,0.071429,0.012987,0.075,0.204082,0.128128,0.208626,0.007313,0.115385,0.006051,0.059406,0.04,0.0,0.137931,0.127660,0.087719,0.155172,0.075758,0.104478,0.188119,0.0,0.0,0.142857,0.966,0.600,0.000000
1,0.0,0.441624,0.636364,0.017647,0.234043,0.030303,0.581395,0.204545,0.021277,0.161491,0.0,0.1250,0.037736,0.05,0.003914,0.076923,0.071429,0.012987,0.050,0.142857,0.115115,0.110331,0.001828,0.038462,0.013616,1.000000,0.08,0.0,0.206897,0.276596,0.122807,0.137931,0.045455,0.238806,0.188119,0.0,0.0,0.107143,1.000,0.143,0.111111
2,1.0,0.204315,0.727273,0.006471,0.276596,0.121212,0.232558,0.204545,0.021277,0.111801,0.0,0.3750,0.018868,0.00,0.037182,0.461538,0.071429,0.000000,0.125,0.346939,0.129129,0.093280,0.000000,0.000000,0.012103,1.000000,0.00,0.0,0.068966,0.361702,0.035088,0.034483,0.015152,0.253731,0.168317,0.0,0.0,0.428571,1.000,0.500,0.111111
3,0.0,0.600254,0.363636,0.008824,0.212766,0.000000,1.000000,0.204545,0.000000,0.124224,0.0,0.1250,0.018868,0.00,0.027397,0.076923,0.035714,0.012987,0.075,0.265306,0.093093,0.102307,0.003656,0.038462,0.003026,1.000000,0.28,0.0,0.344828,0.255319,0.192982,0.206897,0.015152,0.223881,0.158416,0.0,0.0,0.107143,1.000,0.636,0.000000
4,1.0,0.356599,0.181818,0.005078,0.340426,0.000000,1.000000,0.136364,0.000000,0.142857,0.0,0.0000,0.188679,0.00,0.148728,0.000000,0.000000,0.000000,0.000,0.000000,0.122122,0.043129,0.073126,0.000000,0.060514,1.000000,1.00,0.0,0.068966,0.042553,0.035088,0.034483,0.166667,0.029851,0.019802,0.0,0.0,0.000000,1.000,1.000,0.000000

In [28]:
#saving to csv (probably should put it back into SQL somehow?)
X_norm.to_csv(r'C:\Users\drobey\Documents\Coding\Grad School\Data Platforms\Project\accepted_loans_test_norm.csv')

In [45]:
#viewing the columns
X_norm.head()

,loan_status,loan_amnt,emp_length,annual_inc,fico_range_low,inq_last_6mths,mths_since_last_record,open_acc,pub_rec,total_acc,acc_now_delinq,open_acc_6m,open_act_il,open_il_12m,mths_since_rcnt_il,open_rv_12m,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_tl_120dpd_2m,num_tl_30dpd,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies
0,1.0,0.248731,0.272727,0.012286,0.361702,0.090909,1.000000,0.136364,0.000000,0.211180,0.0,0.0625,0.056604,0.00,0.027397,0.153846,0.071429,0.012987,0.075,0.204082,0.128128,0.208626,0.007313,0.115385,0.006051,0.059406,0.04,0.0,0.137931,0.127660,0.087719,0.155172,0.075758,0.104478,0.188119,0.0,0.0,0.142857,0.966,0.600,0.000000
1,0.0,0.441624,0.636364,0.017647,0.234043,0.030303,0.581395,0.204545,0.021277,0.161491,0.0,0.1250,0.037736,0.05,0.003914,0.076923,0.071429,0.012987,0.050,0.142857,0.115115,0.110331,0.001828,0.038462,0.013616,1.000000,0.08,0.0,0.206897,0.276596,0.122807,0.137931,0.045455,0.238806,0.188119,0.0,0.0,0.107143,1.000,0.143,0.111111
2,1.0,0.204315,0.727273,0.006471,0.276596,0.121212,0.232558,0.204545,0.021277,0.111801,0.0,0.3750,0.018868,0.00,0.037182,0.461538,0.071429,0.000000,0.125,0.346939,0.129129,0.093280,0.000000,0.000000,0.012103,1.000000,0.00,0.0,0.068966,0.361702,0.035088,0.034483,0.015152,0.253731,0.168317,0.0,0.0,0.428571,1.000,0.500,0.111111
3,0.0,0.600254,0.363636,0.008824,0.212766,0.000000,1.000000,0.204545,0.000000,0.124224,0.0,0.1250,0.018868,0.00,0.027397,0.076923,0.035714,0.012987,0.075,0.265306,0.093093,0.102307,0.003656,0.038462,0.003026,1.000000,0.28,0.0,0.344828,0.255319,0.192982,0.206897,0.015152,0.223881,0.158416,0.0,0.0,0.107143,1.000,0.636,0.000000
4,1.0,0.356599,0.181818,0.005078,0.340426,0.000000,1.000000,0.136364,0.000000,0.142857,0.0,0.0000,0.188679,0.00,0.148728,0.000000,0.000000,0.000000,0.000,0.000000,0.122122,0.043129,0.073126,0.000000,0.060514,1.000000,1.00,0.0,0.068966,0.042553,0.035088,0.034483,0.166667,0.029851,0.019802,0.0,0.0,0.000000,1.000,1.000,0.000000

In [47]:
#Import model data into mySQL
#Important to run SQL code before this though
from sqlalchemy import create_engine

# create sqlalchemy engine
engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user="root",
                               pw="rootroot",
                               db="loan_data_model"))

X_norm.to_sql('loan_details_model', con = engine, if_exists = 'append', chunksize = 1000, index = False)

In [48]:
#Check to make sure import worked
import pymysql

# create connection
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='rootroot',
                             db='loan_data_model')

# Create cursor
my_cursor = connection.cursor()

# Execute Query
my_cursor.execute("SELECT * from loan_details_model LIMIT 10")

# Fetch the records
result = my_cursor.fetchall()

for i in result:
    print(i)

# Close the connection
connection.close()

(1, 0.248731, 0.272727, 0.0122862, 0.361702, 0.0909091, 1.0, 0.136364, 0.0, 0.21118, 0.0, 0.0625, 0.0566038, 0.0, 0.0273973, 0.153846, 0.0714286, 0.012987, 0.075, 0.204082, 0.128128, 0.208626, 0.00731261, 0.115385, 0.00605144, 0.0594059, 0.04, 0.0, 0.137931, 0.12766, 0.0877193, 0.155172, 0.0757576, 0.104478, 0.188119, 0.0, 0.0, 0.142857, 0.966, 0.6, 0.0)
(0, 0.441624, 0.636364, 0.0176471, 0.234043, 0.030303, 0.581395, 0.204545, 0.0212766, 0.161491, 0.0, 0.125, 0.0377358, 0.05, 0.00391389, 0.0769231, 0.0714286, 0.012987, 0.05, 0.142857, 0.115115, 0.110331, 0.00182815, 0.0384615, 0.0136157, 1.0, 0.08, 0.0, 0.206897, 0.276596, 0.122807, 0.137931, 0.0454545, 0.238806, 0.188119, 0.0, 0.0, 0.107143, 1.0, 0.143, 0.111111)
(1, 0.204315, 0.727273, 0.00647059, 0.276596, 0.121212, 0.232558, 0.204545, 0.0212766, 0.111801, 0.0, 0.375, 0.0188679, 0.0, 0.037182, 0.461538, 0.0714286, 0.0, 0.125, 0.346939, 0.129129, 0.0932798, 0.0, 0.0, 0.0121029, 1.0, 0.0, 0.0, 0.0689655, 0.361702, 0.0350877, 0.0344828, 0.0151515, 0.253731, 0.168317, 0.0, 0.0, 0.428571, 1.0, 0.5, 0.111111)
(0, 0.600254, 0.363636, 0.00882353, 0.212766, 0.0, 1.0, 0.204545, 0.0, 0.124224, 0.0, 0.125, 0.0188679, 0.0, 0.0273973, 0.0769231, 0.0357143, 0.012987, 0.075, 0.265306, 0.0930931, 0.102307, 0.00365631, 0.0384615, 0.00302572, 1.0, 0.28, 0.0, 0.344828, 0.255319, 0.192982, 0.206897, 0.0151515, 0.223881, 0.158416, 0.0, 0.0, 0.107143, 1.0, 0.636, 0.0)
(1, 0.356599, 0.181818, 0.00507765, 0.340426, 0.0, 1.0, 0.136364, 0.0, 0.142857, 0.0, 0.0, 0.188679, 0.0, 0.148728, 0.0, 0.0, 0.0, 0.0, 0.0, 0.122122, 0.0431294, 0.0731261, 0.0, 0.0605144, 1.0, 1.0, 0.0, 0.0689655, 0.0425532, 0.0350877, 0.0344828, 0.166667, 0.0298507, 0.019802, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0)
(1, 0.431472, 0.0, 0.00517647, 0.297872, 0.0, 1.0, 0.0795455, 0.0, 0.149068, 0.0, 0.0, 0.0754717, 0.0, 0.0254403, 0.0, 0.0, 0.012987, 0.0, 0.0204082, 0.112112, 0.112337, 0.0457038, 0.0, 0.0378215, 1.0, 1.0, 0.0, 0.103448, 0.0638298, 0.0526316, 0.0517241, 0.159091, 0.0447761, 0.039604, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0)
(1, 0.387056, 1.0, 0.00529412, 0.617021, 0.030303, 1.0, 0.204545, 0.0, 0.142857, 0.0, 0.1875, 0.0377358, 0.1, 0.00978474, 0.0769231, 0.0357143, 0.0, 0.025, 0.102041, 0.0900901, 0.105316, 0.00365631, 0.0, 0.0151286, 1.0, 0.2, 0.0, 0.0689655, 0.0851064, 0.0701754, 0.0689655, 0.0530303, 0.238806, 0.168317, 0.0, 0.0, 0.142857, 1.0, 0.0, 0.0)
(0, 0.593274, 1.0, 0.00823529, 0.319149, 0.030303, 1.0, 0.113636, 0.0, 0.111801, 0.0, 0.0625, 0.0188679, 0.0, 0.0469667, 0.0384615, 0.0, 0.0, 0.025, 0.0408163, 0.024024, 0.238716, 0.00731261, 0.0576923, 0.0786687, 1.0, 0.16, 0.0, 0.172414, 0.148936, 0.105263, 0.12069, 0.00757576, 0.119403, 0.138614, 0.0, 0.0, 0.0357143, 1.0, 1.0, 0.0)
(0, 0.571066, 0.181818, 0.0129412, 0.212766, 0.0, 1.0, 0.125, 0.0, 0.142857, 0.0, 0.0625, 0.0566038, 0.0, 0.0489237, 0.115385, 0.107143, 0.0, 0.225, 0.102041, 0.159159, 0.351053, 0.00548446, 0.0384615, 0.00453858, 0.232673, 0.0, 0.0277778, 0.172414, 0.106383, 0.140351, 0.189655, 0.0757576, 0.119403, 0.118812, 0.0, 0.0, 0.107143, 0.875, 0.857, 0.0)
(1, 0.873096, 0.727273, 0.0141176, 0.382979, 0.0, 1.0, 0.284091, 0.0, 0.329193, 0.0, 0.125, 0.169811, 0.1, 0.00587084, 0.0, 0.0714286, 0.0, 0.075, 0.142857, 0.254254, 0.11334, 0.0310786, 0.0576923, 0.0257186, 1.0, 0.24, 0.0, 0.0689655, 0.0851064, 0.0877193, 0.155172, 0.212121, 0.19403, 0.217822, 0.0, 0.0, 0.0714286, 0.981, 0.0, 0.0)